### ISSUE TITLE
Plugin Does Not Always Work In IE7/8

### ISSUE THREAD

**Issue by alexbeardsley** [iamthechad/grails-recaptcha#26]
The plugin outputs the script tag immediately in-line where it is present in the GSP. In IE7 and 8, which reCaptca is supposed to be compatible with, script tags aren't executed when inside a div. One workaround is to add the option to not output the script tag via the recaptcha{..} config block, and instead the developer can put the script tag elsewhere.

**Comment by alexbeardsley** [comment]
Created a pull request: https://github.com/iamthechad/grails-recaptcha/pull/27

**Comment by iamthechad** [comment]
Opened new PR #28 to properly target the correct branch.
