### ISSUE TITLE
ReCaptcha on Ajax Forms

### ISSUE THREAD

**Issue by biancarosa** [iamthechad/grails-recaptcha#35]
Hello. I am trying to implement an Ajax form with the grails-recaptcha plugin. 

Haven't really saw a way of doing it. 

Is this even supported? 

Thanks.

**Comment by iamthechad** [comment]
If you want the "old-style" Ajax experience, you'll need to use a pre-1.0 version of the plugin that supports the old captcha.

The new, checkbox style captcha doesn't support Ajax in the same way, but you can create the captcha [using the explicit mode](https://github.com/iamthechad/grails-recaptcha#tag-usage-for-explicit-rendering).

You can look at the [ReCaptcha documentation for explicit mode](https://developers.google.com/recaptcha/docs/display#explicit_render) to see more information.

If this is not the right solution for you, please let me know.

**Comment by biancarosa** [comment]
It its working perfectly :)

I also had two forms in the same page and struggled a bit before finding a answer on ReCaptcha documentation that could work well with the plugin. Can I add my solution to the docs?

**Comment by iamthechad** [comment]
Good to hear you got it working.

I'd love to have more documentation around this area. Feel free to submit a pull request, preferably against the `version1_3_0` branch.
