### ISSUE TITLE
Upgrade to Grails 3.0

### ISSUE THREAD

**Issue by dtamm** [iamthechad/grails-recaptcha#36]
Hey there,

any intentions on upgrading the plugin to be used with grails 3?

Greetings,
Dominik

**Comment by iamthechad** [comment]
Because Grails 3 is so different, I've created a new project for the plugin at https://github.com/iamthechad/grails3-recaptcha.

It is definitely on my todo list, but I just haven't had as much time to work on it recently as I'd hoped.

**Comment by dtamm** [comment]
no problem @iamthechad , if you need any help, just let me know!
