### ISSUE TITLE
1.8 not in Grails central

### ISSUE THREAD

**Issue by olegtim** [iamthechad/grails-recaptcha#53]
Looks like the latest version:  ':recaptcha:1.8.0' is not in the Grails 2.x repo. I am getting an error:

Could not find artifact org.grails.plugins:recaptcha:zip:1.8.0 in grailsCentral (https://repo.grails.org/grails/plugins)

1.7 works fine though: https://repo.grails.org/grails/plugins/org/grails/plugins/recaptcha/

**Comment by iamthechad** [comment]
This is actually an issue with the documentation. There is no released version 1.8. The most recent release is version 1.7. I'll fix up the docs and try to make the current version more obvious.
